use serde_json::{Value, json};

use crate::application::dto::guide_request_document_dto::GuideRequestDocumentDto;
use crate::domain::release_error::ReleaseError;

/// Render the entry and an exact index; keep extended bodies in guide memory.
pub struct AgentGuideMarkdownMapper;

impl AgentGuideMarkdownMapper {
    pub fn map(requests: &[GuideRequestDocumentDto]) -> Result<String, ReleaseError> {
        let request = requests
            .iter()
            .find(|request| request.about() == "guide:kmp-agent")
            .ok_or_else(|| ReleaseError::invalid("agent guide is missing"))?;
        let entries = request.body["memory"]["entries"]
            .as_array()
            .ok_or_else(|| ReleaseError::invalid("agent guide entries are missing"))?;
        let overview = entries
            .iter()
            .find(|entry| entry["id"] == "guide:kmp-agent:overview")
            .ok_or_else(|| ReleaseError::invalid("agent overview is missing"))?;
        let body = overview["text"]
            .as_str()
            .ok_or_else(|| ReleaseError::invalid("agent overview has no text"))?;
        let mut text = format!(
            "# KMP agent entry\n\nGuide version: `{}`. Asset key: `{}`.\n\n{}\n\n",
            overview["metadata"]["guide_version"]
                .as_str()
                .unwrap_or_default(),
            request.body["idempotency_key"].as_str().unwrap_or_default(),
            body.trim()
        );
        text.push_str("## Extended guidance\n\nThese are exact refs in `guide:kmp-agent`, used with `kmp_inspect`; they are not browser URLs. Read the relevant row, not the whole table's bodies.\n\n| Use / tools | Ref |\n| --- | --- |\n");
        for entry in entries {
            if let Some(title) = entry["metadata"]["guide_title"].as_str() {
                let tool_names = entries
                    .iter()
                    .filter(|tool| tool["metadata"]["guide_ref"] == entry["id"])
                    .filter_map(|tool| tool["metadata"]["tool_name"].as_str())
                    .collect::<Vec<_>>();
                let label = if tool_names.is_empty() {
                    title.to_string()
                } else {
                    format!("{title}: `{}`", tool_names.join("`, `"))
                };
                Self::row(&mut text, &label, entry)?;
            }
        }
        for tool in entries
            .iter()
            .filter(|entry| entry["metadata"]["tool_name"].is_string())
        {
            if !entries.iter().any(|entry| {
                entry["id"] == tool["metadata"]["guide_ref"]
                    && entry["metadata"]["guide_title"].is_string()
            }) {
                return Err(ReleaseError::invalid(
                    "a live tool has no indexed extended guide",
                ));
            }
        }
        text.push_str("\n## Worked examples\n\n| Case | Ref |\n| --- | --- |\n");
        for entry in entries {
            if let Some(title) = entry["metadata"]["example_title"].as_str() {
                Self::row(&mut text, title, entry)?;
            }
        }
        let wake = entries
            .iter()
            .find(|entry| entry["metadata"]["tool_name"] == "kmp_wake")
            .ok_or_else(|| ReleaseError::invalid("wake tool reference is missing"))?;
        let arguments = json!({
            "about": request.about(), "ref": wake["metadata"]["guide_ref"],
            "include": {"details": false, "incoming": false, "outgoing": false},
            "budget": {"max_bytes": 40000}
        });
        let arguments = serde_json::to_string_pretty(&arguments).map_err(|error| {
            ReleaseError::invalid(format!("could not encode guide read: {error}"))
        })?;
        text.push_str(&format!("\n## Read a selected node\n\nFor example, consult extended wake guidance with `kmp_inspect`:\n\n```json\n{arguments}\n```\n\nFor another row, replace only `ref` with its exact address. The stable object contains the lesson; adjacent guide links stay unexpanded. Follow any returned page cursor with the same bound arguments. This narrow documentation read does not replace inspection and tracing of actual work evidence. If a ref is missing, check the selected store and guide version, then sync matching assets when needed. Do not guess another ref. The human guide remains `guide:kmp` in ChronoLoom.\n\nGenerated from the versioned editorial source and live tool mapping. Do not edit this file separately.\n"));
        Ok(text)
    }

    fn row(text: &mut String, label: &str, entry: &Value) -> Result<(), ReleaseError> {
        let node_ref = entry["id"]
            .as_str()
            .ok_or_else(|| ReleaseError::invalid("indexed guide entry has no ref"))?;
        text.push_str(&format!("| {label} | `{node_ref}` |\n"));
        Ok(())
    }
}
