//! Where this binary's own guide assets may already be installed.
//!
//! A fresh store has no guide until something writes it. Setup installs the
//! plugin tree and never writes memory, so the first guide read used to be a
//! refusal with a command to type. The assets are on the machine by then,
//! though, and this locator says where: the launcher names the plugin root,
//! a bundled engine sits inside one, and the native hosts keep the installed
//! release in a cache keyed by version. Each candidate is accepted only when
//! its bundle was generated by this binary's version, so a stale cache can
//! never seed a store with another release's guide.
use std::path::{Path, PathBuf};

use super::asset_search::GuideAssetSearch;
use crate::lifecycle::domain::plugin_cache_roots::PluginCacheRoots;
use crate::lifecycle::domain::release_version::ReleaseVersion;

/// The launcher exports the plugin root it started this engine from.
pub const PLUGIN_ROOT_ENV: &str = "KMP_PLUGIN_ROOT";

/// One place the installed guide may be, and what named it.
#[derive(Clone, Debug, PartialEq, Eq)]
struct GuideAssetCandidate {
    origin: &'static str,
    root: PathBuf,
}

/// Candidate plugin roots in the order they are trusted.
#[derive(Clone, Debug, Default)]
pub struct GuideAssetLocator {
    candidates: Vec<GuideAssetCandidate>,
}

impl GuideAssetLocator {
    /// The candidates this process can name from its environment: the
    /// launcher's variable, the plugin a bundled engine lives in, and the
    /// Claude and Codex caches for `version`.
    pub fn from_environment(version: &ReleaseVersion) -> Self {
        let mut candidates = Vec::new();
        if let Some(root) = std::env::var_os(PLUGIN_ROOT_ENV)
            .map(PathBuf::from)
            .filter(|root| !root.as_os_str().is_empty())
        {
            candidates.push(GuideAssetCandidate {
                origin: PLUGIN_ROOT_ENV,
                root,
            });
        }
        if let Some(root) = std::env::current_exe()
            .ok()
            .and_then(|exe| Self::bundled_root(&exe))
        {
            candidates.push(GuideAssetCandidate {
                origin: "bundled engine",
                root,
            });
        }
        let home = std::env::var_os("HOME")
            .or_else(|| std::env::var_os("USERPROFILE"))
            .map(PathBuf::from);
        if let Some(home) = home {
            let codex_home = std::env::var_os("CODEX_HOME")
                .map(PathBuf::from)
                .unwrap_or_else(|| home.join(".codex"));
            let roots = PluginCacheRoots { home, codex_home };
            for (host, root) in roots.installed(version) {
                candidates.push(GuideAssetCandidate {
                    origin: match host {
                        crate::lifecycle::domain::host::Host::Claude => "claude plugin cache",
                        _ => "codex plugin cache",
                    },
                    root: root.as_path().to_path_buf(),
                });
            }
        }
        Self::with_candidates(candidates)
    }

    /// A release package carries the engine at `<plugin>/bin/kmp-mcp`; the
    /// plugin root is then two levels up. Anything else — a cargo target
    /// directory, `~/.cargo/bin` — has no guide beside it and is left out.
    fn bundled_root(exe: &Path) -> Option<PathBuf> {
        let bin = exe.parent()?;
        if bin.file_name()? != "bin" {
            return None;
        }
        let root = bin.parent()?;
        root.join("guide").is_dir().then(|| root.to_path_buf())
    }

    fn with_candidates(candidates: Vec<GuideAssetCandidate>) -> Self {
        let mut unique: Vec<GuideAssetCandidate> = Vec::new();
        for candidate in candidates {
            if !unique.iter().any(|known| known.root == candidate.root) {
                unique.push(candidate);
            }
        }
        Self { candidates: unique }
    }

    /// The first candidate whose assets were generated by `version`, with a
    /// line per candidate that was looked at.
    pub fn locate(&self, version: &ReleaseVersion) -> GuideAssetSearch {
        let mut search = GuideAssetSearch::default();
        for candidate in &self.candidates {
            let display = format!("{}: {}", candidate.origin, candidate.root.display());
            match Self::matching(&candidate.root, version) {
                Ok(()) => {
                    search.searched.push(format!("{display} (matched)"));
                    search.root = Some(candidate.root.clone());
                    return search;
                }
                Err(reason) => search.searched.push(format!("{display} ({reason})")),
            }
        }
        if self.candidates.is_empty() {
            search.searched.push(format!(
                "no candidate: {PLUGIN_ROOT_ENV} is unset, this engine is not inside a plugin, \
                 and no host plugin cache for {} resolves",
                version.as_str()
            ));
        }
        search
    }

    fn matching(root: &Path, version: &ReleaseVersion) -> Result<(), String> {
        if !root.join("guide").join("guide.requests.json").is_file() {
            return Err("no guide assets".to_string());
        }
        let (_, generated_by) = crate::guide::load_assets_with_version(root)?;
        let generated_by = ReleaseVersion::parse(&generated_by)
            .map_err(|_| format!("bundle names an invalid engine version `{generated_by}`"))?;
        if generated_by.represents_same_release(version) {
            Ok(())
        } else {
            Err(format!(
                "generated by {}, this engine is {}",
                generated_by.as_str(),
                version.as_str()
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn version(raw: &str) -> ReleaseVersion {
        ReleaseVersion::parse(raw).expect("version")
    }

    #[test]
    fn a_bundled_engine_names_the_plugin_two_levels_up() {
        let scratch = tempfile::tempdir().expect("scratch");
        let root = scratch.path().join("kmp");
        std::fs::create_dir_all(root.join("bin")).expect("bin");
        std::fs::create_dir_all(root.join("guide")).expect("guide");
        assert_eq!(
            GuideAssetLocator::bundled_root(&root.join("bin").join("kmp-mcp")),
            Some(root.clone())
        );
        assert_eq!(
            GuideAssetLocator::bundled_root(&scratch.path().join("target/debug/kmp-mcp")),
            None
        );
    }

    #[test]
    fn candidates_without_assets_are_reported_and_an_empty_list_says_why() {
        let scratch = tempfile::tempdir().expect("scratch");
        let locator = GuideAssetLocator::with_candidates(vec![GuideAssetCandidate {
            origin: "test",
            root: scratch.path().to_path_buf(),
        }]);
        let search = locator.locate(&version("0.1.0"));
        assert_eq!(search.root, None);
        assert_eq!(search.searched.len(), 1);
        assert!(search.searched[0].ends_with("(no guide assets)"));

        let search = GuideAssetLocator::with_candidates(Vec::new()).locate(&version("0.1.0"));
        assert_eq!(search.root, None);
        assert!(search.searched[0].starts_with("no candidate:"));
    }

    #[test]
    fn duplicate_roots_are_looked_at_once() {
        let scratch = tempfile::tempdir().expect("scratch");
        let candidate = GuideAssetCandidate {
            origin: "test",
            root: scratch.path().to_path_buf(),
        };
        let locator = GuideAssetLocator::with_candidates(vec![candidate.clone(), candidate]);
        assert_eq!(locator.candidates.len(), 1);
    }

    #[test]
    fn the_repository_assets_match_only_their_own_engine_version() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../plugins/kmp");
        let locator = GuideAssetLocator::with_candidates(vec![GuideAssetCandidate {
            origin: "test",
            root: root.clone(),
        }]);
        let current = ReleaseVersion::current();
        assert_eq!(locator.locate(&current).root, Some(root));
        let other = locator.locate(&version("0.0.1"));
        assert_eq!(other.root, None);
        assert!(other.searched[0].contains("generated by"));
    }
}
