pub(crate) mod app_view_take_control;
pub(crate) mod app_view_undo;
pub(crate) mod app_visual_projection;
pub(crate) mod ask;
pub(crate) mod condense;
pub(crate) mod curate;
pub(crate) mod guide;
pub(crate) mod ingest;
pub(crate) mod inspect;
pub(crate) mod relabel;
pub(crate) mod relate;
pub(crate) mod summaries_audit;
pub(crate) mod time;
pub(crate) mod trace;
mod trace_condense;
mod trace_seek;
pub(crate) mod view_apply_intent;
pub(crate) mod view_get_state;
pub(crate) mod view_open;
pub(crate) mod wake;
pub(crate) mod write_memory;

pub(crate) mod app_memory_nodes;
