[package]
name = "rehydration-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rehydration-application.workspace = true
rehydration-domain.workspace = true

[dev-dependencies]
rehydration-adapter-embedded.workspace = true
rehydration-testkit.workspace = true
tempfile = "3.26.0"
tokio.workspace = true
