[package]
name = "kmp-observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["otel"]
otel = [
    "dep:opentelemetry",
    "dep:opentelemetry-otlp",
    "dep:opentelemetry_sdk",
    "dep:tokio",
    "dep:tonic",
    "dep:tracing-opentelemetry",
    "dep:tracing-subscriber",
]

[dependencies]
opentelemetry = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
kmp-domain = { path = "../kmp-domain" }
tokio = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
tonic = { workspace = true, optional = true }
tracing.workspace = true
tracing-opentelemetry = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
